# Generated by Django 6.0 on 2025-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customer_type',
            field=models.CharField(choices=[('new', '새로운 손님'), ('call', '손님 호출'), ('delivery', '배달원')], default='new', max_length=10),
        ),
    ]
